services:
  pgdatabase:
    image: postgres:15
    environment:
      - POSTGRES_USER=root2
      - POSTGRES_PASSWORD=root2
      - POSTGRES_DB=ny_taxi
    volumes:
      - "dtc_postgres_volume_local:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    networks:
      - airflow

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com 
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8081:80"
    networks:
      - airflow

    
networks:
  airflow:
    external: true
    name: airflow2025_default

volumes:
  dtc_postgres_volume_local: